export enum OperationApiResponseCodes {
  CardDataNotFilled = -21,
  HashAlreadyUsed = -20,
  HashExpired = -19,
  CantChangeToSameEmail = -18,
  EmailAlreadyRegistered = -17,
  InvalidTimeToken = -16,
  TimeTokenExpired = -15,
  UserAlreadyExists = -14,
  NotValidRequestData = -13,
  NotValidFullName = -12,
  NotValidEmail = -11,
  NotValidPassword = -10,
  NotValidEducationRequestData = -5,
  NoResponseData = -4,
  NoRequestData = -3,
  UserNotFound = -2,
  Fail = -1,
  Ok = 0,
}
